### ISSUE TITLE
No request in apollo context (context is an empty object)

### ISSUE THREAD

**Issue by mattlgroff** [elysiajs/elysia-apollo#1]
When I set the `context` in the Apollo Server Plugin, it doesn't get the `request` object. I believe this is because of the way Apollo Server 4 changed their context object.

My code:
```javascript
// Apollo Server Plugin for Elysia
app.use(
  apollo({
      path: '/graphql',
      enablePlayground: true, // Default is disabled in production
      typeDefs, // Import schema from .graphql file
      resolvers, // Import resolvers from resolvers.js,
      context: async (foo) => {

        console.log('foo', foo); // {}

        return {
          dataSources: {

          }
        }
      }
  }),
);
```

In this case, any request I make the `foo` object is empty `{}` with no request information.

https://www.apollographql.com/docs/apollo-server/migration/#context-initialization-function
![image](https://user-images.githubusercontent.com/3247978/215298335-53fef4b9-6110-45bf-90e0-acb6f2284550.png)

Could this be done in a similar way to how the express middleware for Apollo Server 4 handles the change?

Or maybe I'm missing something obvious to capture the request object in my context, if so, sorry!

**Comment by SaltyAom** [comment]
Because Elysia is based on Web Standard `Request` and `Response` which is different from Node's `HttpRequest` and `HttpResponse` that Express use, result in `req`, and `res` being undefined in context.

However, we can add a web standard's `Request` instead to make a suitable equivalent.

**Comment by SaltyAom** [comment]
Should be working in [e26dc99](https://github.com/elysiajs/elysia-apollo/commit/e26dc99db0166078f316d27a010e098c2a06c2fd).

However, do note that the `req` and `res` is not as same as Apollo, but it's Elysia's Context instead.
